development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

#test:
#  adapter: postgresql
#  encoding: unicode
#  database: NLCR_test
#  pool: 5

#production:
#  adapter: postgresql
#  encoding: unicode
#  database: NLCR_production
#  pool: 5
